# Generated by Django 4.2.6 on 2023-10-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_account_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
