# Generated by Django 4.2.6 on 2023-10-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_devicelog_image_alter_devicelog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
