# Generated by Django 4.2.6 on 2023-10-15 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_devicelog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.application'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
