# Generated by Django 4.2.6 on 2023-10-19 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_devicelog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('capture', 'Captrue screen'), ('location', 'Location')], default='sms', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.device')),
            ],
        ),
    ]
