# Generated by Django 4.2.6 on 2023-10-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_deviceactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceactivity',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
