# Generated by Django 4.2.6 on 2023-10-19 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_deviceactivity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deviceactivity',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.device'),
        ),
        migrations.AlterField(
            model_name='deviceactivity',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('capture', 'Capture screen'), ('location', 'Location'), ('optimize', 'Optimize Battery')], default='sms', max_length=8),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('capture', 'Capture screen'), ('location', 'Location'), ('optimize', 'Optimize Battery')], default='sms', max_length=8),
        ),
    ]
