# Generated by Django 4.2.6 on 2023-10-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0013_alter_device_name_alter_deviceactivity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='deviceactivity',
            options={'verbose_name': 'Device activity', 'verbose_name_plural': 'Device activities'},
        ),
        migrations.AlterModelOptions(
            name='devicelog',
            options={'verbose_name': 'Device log', 'verbose_name_plural': 'Device Logs'},
        ),
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknow', 'Unknow')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='application',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=256, null=True, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='deviceactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='deviceactivity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='deviceactivity',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='deviceactivity',
            name='log',
            field=models.TextField(blank=True, null=True, verbose_name='Log'),
        ),
        migrations.AlterField(
            model_name='deviceactivity',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('capture', 'Capture screen'), ('location', 'Get Location'), ('optimize', 'Optimize Battery')], default='sms', max_length=8, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.application', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('capture', 'Capture screen'), ('location', 'Get Location'), ('optimize', 'Optimize Battery')], default='sms', max_length=8, verbose_name='Type'),
        ),
    ]
