# Generated by Django 4.2.6 on 2023-10-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_account_options_alter_application_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='image',
            new_name='avatar',
        ),
    ]
