# Generated by Django 4.2.6 on 2023-11-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_image_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_interval',
            field=models.BooleanField(default=False, verbose_name='Loop capture'),
        ),
        migrations.AlterField(
            model_name='deviceactivity',
            name='type',
            field=models.CharField(choices=[('capture_loop', 'Loop capture'), ('capture', 'Capture screen'), ('location', 'Get Location'), ('optimize', 'Optimize Battery')], default='sms', max_length=12, verbose_name='Type'),
        ),
    ]
