# Generated by Django 4.2.6 on 2024-01-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_device_is_interval_alter_deviceactivity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='ignore',
            field=models.BooleanField(default=False, verbose_name='Ignore'),
        ),
    ]
